# Generated by Django 4.1.6 on 2023-03-25 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование товара')),
                ('category', models.CharField(choices=[('Other', 'Разное'), ('Phone', 'Телефоны'), ('Laptop', 'Ноутбуки'), ('TV', 'Телевизоры')], default='Other', max_length=50, verbose_name='Категория товара')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание товара')),
                ('photo', models.CharField(default='blank.jpg', max_length=50, verbose_name='Изображение продукта')),
                ('average_grade', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Средняя Оценка')),
                ('average_grade_stars', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Средняя оценка звездочками')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation', models.CharField(choices=[('Moderate', 'Модерировано'), ('No_moderate', 'Немодерировано')], default='No_moderate', max_length=50, verbose_name='Модерация')),
                ('text', models.CharField(max_length=200, verbose_name='Текст отзыва')),
                ('grade', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Оценка')),
                ('grade_stars', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Оценка звездочками')),
                ('author', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('product', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webapp.product', verbose_name='Товары')),
            ],
        ),
    ]
