# Generated by Django 4.1.6 on 2023-03-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание товара'),
        ),
    ]
