# Generated by Django 4.1.6 on 2023-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Other', 'Разное'), ('Phone', 'Телефоны'), ('Laptop', 'Ноутбуки'), ('TV', 'Телевизоры')], default='Other', max_length=200, verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(default='blank.jpg', max_length=200, verbose_name='Изображение продукта'),
        ),
    ]
